import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
	return (
		<div className="bg-slate-400">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="">
				<h1 className="">Welcome to trivialspace</h1>

				<p className="">
					Get started by editing <code className="">pages/index.tsx</code>
				</p>
			</main>

			<footer className="">
				by Thomas Gorny <a href="https://trival.xyz">trival.xyz</a>{' '}
			</footer>
		</div>
	)
}

export default Home
